package specsync

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"html"
	"io"
	"net/url"
	"strconv"
	"strings"
	"unicode"
)

const xhtmlNamespace = "http://www.w3.org/1999/xhtml"

type node struct {
	name     xml.Name
	attrs    []xml.Attr
	text     string
	children []*node
}

// Convert converts one XHTML document to deterministic UTF-8 Markdown.
func Convert(source io.Reader, sourceURL, digest string) ([]byte, error) {
	if source == nil {
		return nil, fmt.Errorf("read XHTML: reader must not be nil")
	}
	raw, err := io.ReadAll(source)
	if err != nil {
		return nil, fmt.Errorf("read XHTML: %w", err)
	}
	root, err := parseXHTML(expandHTMLEntities(raw))
	if err != nil {
		return nil, err
	}
	base, err := url.Parse(sourceURL)
	if err != nil {
		return nil, fmt.Errorf("parse source URL %q: %w", sourceURL, err)
	}
	reservedIDs := make(map[string]struct{})
	collectOriginalIDs(root, reservedIDs)
	renderer := markdownRenderer{
		baseURL:      base,
		anchorCounts: make(map[string]int),
		reservedIDs:  reservedIDs,
		usedIDs:      make(map[string]struct{}),
	}
	renderer.write("<!-- Code generated by go run ./cmd/specsync; DO NOT EDIT. -->\n")
	renderer.write("<!-- Source: " + escapeComment(sourceURL) + " -->\n")
	renderer.write("<!-- SHA-256: " + escapeComment(digest) + " -->\n\n")
	renderer.renderBlock(root)
	output := strings.TrimRight(renderer.output.String(), " \t\n") + "\n"
	return []byte(output), nil
}

func expandHTMLEntities(raw []byte) []byte {
	var output bytes.Buffer
	for index := 0; index < len(raw); {
		if raw[index] != '&' {
			output.WriteByte(raw[index])
			index++
			continue
		}
		end := bytes.IndexByte(raw[index:], ';')
		if end < 0 {
			output.WriteByte(raw[index])
			index++
			continue
		}
		end += index
		entity := string(raw[index : end+1])
		if isXMLBuiltinEntity(entity) || !isNamedEntity(entity) {
			output.WriteString(entity)
			index = end + 1
			continue
		}
		expanded := html.UnescapeString(entity)
		if expanded == entity || strings.Contains(expanded, ";") {
			output.WriteString(entity)
		} else {
			output.WriteString(expanded)
		}
		index = end + 1
	}
	return output.Bytes()
}

func isXMLBuiltinEntity(entity string) bool {
	switch entity {
	case "&amp;", "&lt;", "&gt;", "&quot;", "&apos;":
		return true
	default:
		return false
	}
}

func isNamedEntity(entity string) bool {
	if len(entity) < 3 || entity[0] != '&' || entity[len(entity)-1] != ';' {
		return false
	}
	for _, character := range entity[1 : len(entity)-1] {
		if !unicode.IsLetter(character) && !unicode.IsDigit(character) {
			return false
		}
	}
	return true
}

func parseXHTML(raw []byte) (*node, error) {
	decoder := xml.NewDecoder(bytes.NewReader(raw))
	var root *node
	stack := make([]*node, 0, 32)
	for {
		token, err := decoder.Token()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("parse XHTML at byte %d: %w", decoder.InputOffset(), err)
		}
		switch value := token.(type) {
		case xml.StartElement:
			current := &node{name: value.Name, attrs: append([]xml.Attr(nil), value.Attr...)}
			if len(stack) == 0 {
				if root != nil {
					return nil, fmt.Errorf("parse XHTML at byte %d: multiple root elements", decoder.InputOffset())
				}
				root = current
			} else {
				parent := stack[len(stack)-1]
				parent.children = append(parent.children, current)
			}
			stack = append(stack, current)
		case xml.EndElement:
			if len(stack) == 0 {
				return nil, fmt.Errorf("parse XHTML at byte %d: unexpected closing element %q", decoder.InputOffset(), value.Name.Local)
			}
			stack = stack[:len(stack)-1]
		case xml.CharData:
			if len(stack) != 0 {
				parent := stack[len(stack)-1]
				parent.children = append(parent.children, &node{text: string(value)})
			}
		}
	}
	if root == nil {
		return nil, fmt.Errorf("parse XHTML: document has no root element")
	}
	if root.name.Local != "html" || root.name.Space != xhtmlNamespace {
		return nil, fmt.Errorf("parse XHTML: root must be html in namespace %q", xhtmlNamespace)
	}
	return root, nil
}

type markdownRenderer struct {
	output       strings.Builder
	baseURL      *url.URL
	anchorCounts map[string]int
	reservedIDs  map[string]struct{}
	usedIDs      map[string]struct{}
}

func collectOriginalIDs(current *node, ids map[string]struct{}) {
	for _, id := range targetIDs(current) {
		if id != "" {
			ids[id] = struct{}{}
		}
	}
	for _, child := range current.children {
		collectOriginalIDs(child, ids)
	}
}

func (r *markdownRenderer) write(value string) {
	r.output.WriteString(value)
}

func (r *markdownRenderer) renderBlock(current *node) {
	if current.name.Local == "" {
		return
	}
	name := strings.ToLower(current.name.Local)
	if name == "head" || name == "script" || name == "style" {
		return
	}
	if level, heading := headingLevel(name); heading {
		r.renderHeading(current, level)
		return
	}
	r.renderAnchors(current, false)
	r.renderSemanticClass(current)
	if isLiteralContainer(current) {
		r.renderLiteralContainer(current)
		return
	}
	if hasClass(current, "constraintlist") {
		r.renderConstraintList(current)
		return
	}
	switch name {
	case "html", "body":
		for _, child := range current.children {
			r.renderBlock(child)
		}
	case "pre":
		r.renderPre(current)
	case "p":
		r.renderParagraph(current)
	case "ul", "ol":
		r.renderList(current, name == "ol")
	case "dl":
		r.renderDefinitionList(current)
	case "table":
		r.renderTable(current)
	case "blockquote":
		text := normalizeProse(r.inlineChildren(current))
		if text != "" {
			for _, line := range strings.Split(text, "\n") {
				r.write("> " + line + "\n")
			}
			r.write("\n")
		}
	default:
		r.renderContainer(current)
	}
}

func (r *markdownRenderer) renderContainer(current *node) {
	var inlineRun strings.Builder
	flush := func() {
		text := normalizeProse(inlineRun.String())
		if text != "" {
			r.write(text + "\n\n")
		}
		inlineRun.Reset()
	}
	for _, child := range current.children {
		if child.name.Local != "" && isBlockElement(strings.ToLower(child.name.Local)) {
			flush()
			r.renderBlock(child)
			continue
		}
		inlineRun.WriteString(r.inline(child))
	}
	flush()
}

func isBlockElement(name string) bool {
	switch name {
	case "address", "blockquote", "div", "dl", "fieldset", "form", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "ol", "p", "pre", "table", "ul":
		return true
	default:
		return false
	}
}

func headingLevel(name string) (int, bool) {
	if len(name) != 2 || name[0] != 'h' || name[1] < '1' || name[1] > '6' {
		return 0, false
	}
	return int(name[1] - '0'), true
}

func (r *markdownRenderer) renderHeading(current *node, level int) {
	r.renderAnchors(current, true)
	text := normalizeProse(r.inlineChildrenSkippingTargets(current))
	if text == "" {
		return
	}
	r.write(strings.Repeat("#", level) + " " + text + "\n\n")
}

func (r *markdownRenderer) renderParagraph(current *node) {
	text := normalizeProse(r.inlineChildren(current))
	if text != "" {
		r.write(text + "\n\n")
	}
}

func (r *markdownRenderer) renderPre(current *node) {
	for _, child := range current.children {
		r.renderDescendantAnchors(child)
	}
	literal := collectText(current)
	literal = strings.ReplaceAll(literal, "\r\n", "\n")
	literal = strings.ReplaceAll(literal, "\r", "\n")
	r.renderFencedLiteral(literal)
}

func (r *markdownRenderer) renderFencedLiteral(literal string) {
	fence := strings.Repeat("`", longestRun(literal, '`')+1)
	if len(fence) < 3 {
		fence = "```"
	}
	r.write(fence + "\n" + literal)
	if !strings.HasSuffix(literal, "\n") {
		r.write("\n")
	}
	r.write(fence + "\n\n")
}

func isLiteralContainer(current *node) bool {
	return hasClass(current, "element-syntax") || hasClass(current, "element-syntax-1")
}

func hasClass(current *node, wanted string) bool {
	for _, class := range strings.Fields(attr(current, "class")) {
		if class == wanted {
			return true
		}
	}
	return false
}

func (r *markdownRenderer) renderLiteralContainer(current *node) {
	for _, child := range current.children {
		r.renderDescendantAnchors(child)
	}
	var literal strings.Builder
	collectLiteralText(current, &literal)
	lines := strings.Split(strings.ReplaceAll(literal.String(), "\r", ""), "\n")
	for index, line := range lines {
		lines[index] = normalizeLiteralLine(line)
	}
	r.renderFencedLiteral(strings.Trim(strings.Join(lines, "\n"), "\n"))
}

func collectLiteralText(current *node, output *strings.Builder) {
	if current.name.Local == "" {
		output.WriteString(current.text)
		return
	}
	if strings.EqualFold(current.name.Local, "br") {
		output.WriteByte('\n')
		return
	}
	for _, child := range current.children {
		collectLiteralText(child, output)
	}
}

func normalizeLiteralLine(line string) string {
	line = strings.Trim(line, " \t\r\n")
	indent := 0
	for strings.HasPrefix(line, "\u00a0") {
		indent++
		line = strings.TrimPrefix(line, "\u00a0")
	}
	line = strings.ReplaceAll(line, "\u00a0", " ")
	return strings.Repeat(" ", indent) + normalizeProse(line)
}

func (r *markdownRenderer) renderDescendantAnchors(current *node) {
	r.renderAnchors(current, false)
	for _, child := range current.children {
		r.renderDescendantAnchors(child)
	}
}

func longestRun(value string, target byte) int {
	longest, current := 0, 0
	for index := 0; index < len(value); index++ {
		if value[index] != target {
			current = 0
			continue
		}
		current++
		if current > longest {
			longest = current
		}
	}
	return longest
}

func (r *markdownRenderer) renderList(current *node, ordered bool) {
	item := 0
	for _, child := range current.children {
		if child.name.Local != "li" {
			continue
		}
		item++
		prefix := "- "
		if ordered {
			prefix = strconv.Itoa(item) + ". "
		}
		r.renderListItem(child, prefix)
	}
	if item != 0 {
		r.write("\n")
	}
}

func (r *markdownRenderer) renderListItem(item *node, prefix string) {
	itemRenderer := markdownRenderer{
		baseURL:      r.baseURL,
		anchorCounts: r.anchorCounts,
		reservedIDs:  r.reservedIDs,
		usedIDs:      r.usedIDs,
	}
	itemRenderer.renderAnchors(item, false)
	itemRenderer.renderSemanticClass(item)
	itemRenderer.renderContainer(item)
	content := strings.TrimRight(itemRenderer.output.String(), " \t\n")
	if content == "" {
		r.write(strings.TrimSpace(prefix) + "\n")
		return
	}
	lines := strings.Split(content, "\n")
	r.write(prefix + lines[0] + "\n")
	indent := strings.Repeat(" ", len(prefix))
	for _, line := range lines[1:] {
		if line == "" {
			r.write("\n")
			continue
		}
		r.write(indent + line + "\n")
	}
}

func (r *markdownRenderer) renderConstraintList(current *node) {
	item := 0
	for _, child := range current.children {
		if !hasClass(child, "clnumber") {
			continue
		}
		item++
		withoutNumber := constraintItemWithoutNumber(child)
		r.renderListItem(withoutNumber, strconv.Itoa(item)+". ")
	}
	if item != 0 {
		r.write("\n")
	}
}

func constraintItemWithoutNumber(item *node) *node {
	copyItem := *item
	copyItem.children = append([]*node(nil), item.children...)
	for index, child := range copyItem.children {
		if child.name.Local != "" {
			continue
		}
		copyText := *child
		copyText.text = stripConstraintNumber(child.text)
		copyItem.children[index] = &copyText
		break
	}
	return &copyItem
}

func stripConstraintNumber(value string) string {
	trimmed := strings.TrimLeftFunc(value, unicode.IsSpace)
	end := 0
	digit := false
	for end < len(trimmed) {
		character := trimmed[end]
		if character >= '0' && character <= '9' {
			digit = true
			end++
			continue
		}
		if character == '.' {
			end++
			continue
		}
		break
	}
	if !digit || end < len(trimmed) && !unicode.IsSpace(rune(trimmed[end])) {
		return value
	}
	return strings.TrimLeftFunc(trimmed[end:], unicode.IsSpace)
}

func (r *markdownRenderer) renderDefinitionList(current *node) {
	for _, child := range current.children {
		r.renderAnchors(child, false)
		r.renderSemanticClass(child)
		text := normalizeProse(r.inlineChildren(child))
		switch child.name.Local {
		case "dt":
			r.write("**" + text + "**\n\n")
		case "dd":
			r.write(text + "\n\n")
		}
	}
}

func (r *markdownRenderer) renderTable(current *node) {
	rows := r.tableRows(current)
	var pending [][]string
	flush := func() {
		r.writeMarkdownTable(pending)
		pending = nil
	}
	for _, row := range rows {
		r.renderAnchors(row, false)
		r.renderSemanticClass(row)
		cells := make([]string, 0)
		var nestedCells []*node
		for _, child := range row.children {
			if child.name.Local == "td" || child.name.Local == "th" {
				r.renderAnchors(child, false)
				r.renderSemanticClass(child)
				if hasDescendantElement(child, "table") {
					text := strings.ReplaceAll(normalizeProse(r.inlineChildrenWithoutTables(child)), "|", "\\|")
					if text != "" {
						cells = append(cells, text)
					}
					nestedCells = append(nestedCells, child)
					continue
				}
				cells = append(cells, strings.ReplaceAll(normalizeProse(r.inlineChildren(child)), "|", "\\|"))
			}
		}
		if len(cells) != 0 {
			pending = append(pending, cells)
		}
		if len(nestedCells) != 0 {
			flush()
			for _, cell := range nestedCells {
				r.renderNestedTables(cell)
			}
		}
	}
	flush()
}

func (r *markdownRenderer) writeMarkdownTable(rows [][]string) {
	width := 0
	for _, row := range rows {
		if len(row) > width {
			width = len(row)
		}
	}
	if width == 0 {
		return
	}
	writeRow := func(row []string) {
		padded := make([]string, width)
		copy(padded, row)
		r.write("| " + strings.Join(padded, " | ") + " |\n")
	}
	writeRow(rows[0])
	delimiter := make([]string, width)
	for index := range delimiter {
		delimiter[index] = "---"
	}
	writeRow(delimiter)
	for _, row := range rows[1:] {
		writeRow(row)
	}
	r.write("\n")
}

func hasDescendantElement(current *node, name string) bool {
	for _, child := range current.children {
		if strings.EqualFold(child.name.Local, name) || hasDescendantElement(child, name) {
			return true
		}
	}
	return false
}

func (r *markdownRenderer) inlineChildrenWithoutTables(current *node) string {
	var output strings.Builder
	for _, child := range current.children {
		if strings.EqualFold(child.name.Local, "table") {
			continue
		}
		output.WriteString(r.inline(child))
	}
	return output.String()
}

func (r *markdownRenderer) renderNestedTables(current *node) {
	for _, child := range current.children {
		if strings.EqualFold(child.name.Local, "table") {
			r.renderBlock(child)
			continue
		}
		r.renderNestedTables(child)
	}
}

func (r *markdownRenderer) tableRows(current *node) []*node {
	var rows []*node
	for _, child := range current.children {
		switch child.name.Local {
		case "tr":
			rows = append(rows, child)
		case "thead", "tbody", "tfoot":
			r.renderAnchors(child, false)
			r.renderSemanticClass(child)
			rows = append(rows, r.tableRows(child)...)
		case "caption":
			r.renderBlock(child)
		default:
			r.renderDescendantAnchors(child)
		}
	}
	return rows
}

func (r *markdownRenderer) renderAnchors(current *node, includeDescendants bool) {
	ids := targetIDs(current)
	if includeDescendants {
		for _, child := range current.children {
			if child.name.Local == "a" {
				ids = append(ids, targetIDs(child)...)
			}
		}
	}
	seen := make(map[string]struct{}, len(ids))
	for _, id := range ids {
		if id == "" {
			continue
		}
		if _, duplicateHere := seen[id]; duplicateHere {
			continue
		}
		seen[id] = struct{}{}
		r.write(r.anchorMarkup(id) + "\n")
	}
}

func (r *markdownRenderer) anchorMarkup(id string) string {
	r.anchorCounts[id]++
	outputID := id
	comment := ""
	if r.anchorCounts[id] > 1 {
		outputID = r.allocateDuplicateID(id, r.anchorCounts[id])
		comment = "<!-- Source fragment " + escapeComment(id) + " maps to " + escapeComment(outputID) + ". -->"
	}
	r.usedIDs[outputID] = struct{}{}
	return comment + "<a id=\"" + html.EscapeString(outputID) + "\"></a>"
}

func (r *markdownRenderer) allocateDuplicateID(id string, ordinal int) string {
	base := "goxsd-duplicate-" + url.PathEscape(id) + "-"
	for {
		candidate := base + strconv.Itoa(ordinal)
		_, reserved := r.reservedIDs[candidate]
		_, used := r.usedIDs[candidate]
		if !reserved && !used {
			return candidate
		}
		ordinal++
	}
}

func targetIDs(current *node) []string {
	var ids []string
	if id := attr(current, "id"); id != "" {
		ids = append(ids, id)
	}
	if current.name.Local == "a" {
		if name := attr(current, "name"); name != "" && name != attr(current, "id") {
			ids = append(ids, name)
		}
	}
	return ids
}

var semanticClasses = map[string]struct{}{
	"note": {}, "exampleOuter": {}, "exampleInner": {}, "constraint": {},
	"constraintnote": {}, "component": {}, "schemaComp": {}, "prod": {},
	"lhs": {}, "scrap": {},
}

func (r *markdownRenderer) renderSemanticClass(current *node) {
	markup := semanticClassMarkup(current)
	if markup != "" {
		r.write(markup + "\n")
	}
}

func semanticClassMarkup(current *node) string {
	classes := strings.Fields(attr(current, "class"))
	var kept []string
	for _, class := range classes {
		if _, ok := semanticClasses[class]; ok {
			kept = append(kept, class)
		}
	}
	if len(kept) != 0 {
		return "<!-- XHTML class: " + escapeComment(strings.Join(kept, " ")) + " -->"
	}
	return ""
}

func (r *markdownRenderer) inlineChildren(current *node) string {
	var output strings.Builder
	for _, child := range current.children {
		output.WriteString(r.inline(child))
	}
	return output.String()
}

func (r *markdownRenderer) inlineChildrenSkippingTargets(current *node) string {
	var output strings.Builder
	for _, child := range current.children {
		if child.name.Local == "a" && attr(child, "href") == "" {
			output.WriteString(r.inlineChildren(child))
			continue
		}
		output.WriteString(r.inline(child))
	}
	return output.String()
}

func (r *markdownRenderer) inline(current *node) string {
	if current.name.Local == "" {
		return escapeMarkdown(current.text)
	}
	name := strings.ToLower(current.name.Local)
	anchors := ""
	for _, id := range targetIDs(current) {
		anchors += r.anchorMarkup(id)
	}
	if semantic := semanticClassMarkup(current); semantic != "" {
		anchors += semantic + " "
	}
	switch name {
	case "a":
		content := r.inlineChildren(current)
		href := attr(current, "href")
		if href == "" {
			return anchors + content
		}
		return anchors + "[" + normalizeProse(content) + "](" + r.resolveLink(href) + ")"
	case "code", "tt":
		anchors += r.descendantAnchorMarkup(current)
		literal := collectText(current)
		delimiter := strings.Repeat("`", longestRun(literal, '`')+1)
		if delimiter == "`" && (strings.HasPrefix(literal, " ") || strings.HasSuffix(literal, " ")) {
			return anchors + delimiter + " " + literal + " " + delimiter
		}
		return anchors + delimiter + literal + delimiter
	case "em", "i":
		return anchors + "*" + r.inlineChildren(current) + "*"
	case "strong", "b":
		return anchors + "**" + r.inlineChildren(current) + "**"
	case "sup", "sub":
		anchors += r.descendantAnchorMarkup(current)
		content := html.EscapeString(normalizeProse(collectText(current)))
		return anchors + "<" + name + ">" + content + "</" + name + ">"
	case "img":
		alternative := attr(current, "alt")
		if alternative == "" {
			alternative = "Image"
		}
		source := attr(current, "src")
		return anchors + "![" + escapeMarkdown(alternative) + "](<" + r.resolveLink(source) + ">)"
	case "br":
		return anchors + "  \n"
	case "pre":
		literal := strings.ReplaceAll(collectText(current), "\r\n", "\n")
		literal = strings.ReplaceAll(literal, "\r", "\n")
		return anchors + r.descendantAnchorMarkup(current) + escapedHTMLPre(literal)
	default:
		return anchors + r.inlineChildren(current)
	}
}

func escapedHTMLPre(literal string) string {
	literal = html.EscapeString(literal)
	literal = strings.ReplaceAll(literal, " ", "&#32;")
	literal = strings.ReplaceAll(literal, "\t", "&#9;")
	literal = strings.ReplaceAll(literal, "\n", "&#10;")
	return "<pre><code>" + literal + "</code></pre>"
}

func (r *markdownRenderer) descendantAnchorMarkup(current *node) string {
	var markup strings.Builder
	for _, child := range current.children {
		for _, id := range targetIDs(child) {
			markup.WriteString(r.anchorMarkup(id))
		}
		markup.WriteString(r.descendantAnchorMarkup(child))
	}
	return markup.String()
}

func (r *markdownRenderer) resolveLink(reference string) string {
	parsed, err := url.Parse(reference)
	if err != nil {
		return reference
	}
	if strings.HasPrefix(reference, "#") {
		return reference
	}
	return r.baseURL.ResolveReference(parsed).String()
}

func attr(current *node, name string) string {
	for _, attribute := range current.attrs {
		if attribute.Name.Local == name {
			return attribute.Value
		}
	}
	return ""
}

func collectText(current *node) string {
	if current.name.Local == "" {
		return current.text
	}
	var output strings.Builder
	for _, child := range current.children {
		output.WriteString(collectText(child))
	}
	return output.String()
}

func normalizeProse(value string) string {
	return strings.Join(strings.Fields(value), " ")
}

func escapeMarkdown(value string) string {
	replacer := strings.NewReplacer("\\", "\\\\", "`", "\\`", "*", "\\*", "_", "\\_", "[", "\\[", "]", "\\]")
	return replacer.Replace(value)
}

func escapeComment(value string) string {
	return strings.ReplaceAll(value, "--", "- -")
}
