package specsync

import (
	"strings"
	"testing"
)

func TestConvertPreservesResearchStructure(t *testing.T) {
	t.Parallel()
	input := `<?xml version="1.0"?>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Fixture</title></head><body>
<h2><a name="intro" id="intro"></a>1 Introduction</h2>
<p id="target">See <a href="#intro">the intro</a> and <a href="other.html#rule">a rule</a>.</p>
<div class="exampleOuter"><p>Example &amp; entity&nbsp;text.</p><pre xml:space="preserve"><code>&lt;xs:schema&gt;
  value ` + "```" + ` &amp; more
&lt;/xs:schema&gt;</code></pre></div>
<div id="target">duplicate</div><div id="Target">case distinct</div>
<div class="constraint schemaComp"><p><span class="prod lhs">Schema Representation Constraint:</span> label</p></div>
<ul><li id="list-target">listed <code id="code-target">literal</code></li></ul>
<dl><dt id="term-target">Term</dt><dd id="definition-target">Definition</dd></dl>
<table><tbody id="body-target"><tr id="row-target"><td id="cell-target">cell</td></tr></tbody></table>
</body></html>`
	first, err := Convert(strings.NewReader(input), "https://example.test/spec/structures.html", strings.Repeat("a", 64))
	if err != nil {
		t.Fatalf("Convert() error = %v", err)
	}
	second, err := Convert(strings.NewReader(input), "https://example.test/spec/structures.html", strings.Repeat("a", 64))
	if err != nil {
		t.Fatalf("second Convert() error = %v", err)
	}
	if string(first) != string(second) {
		t.Fatal("Convert() is not deterministic")
	}
	wants := []string{
		"<!-- Code generated by go run ./cmd/specsync; DO NOT EDIT. -->",
		`<a id="intro"></a>`,
		"## 1 Introduction",
		"<a id=\"target\"></a>\nSee [the intro](#intro) and [a rule](https://example.test/spec/other.html#rule).",
		"<!-- XHTML class: exampleOuter -->",
		"Example & entity text.",
		"````\n<xs:schema>\n  value ``` & more\n</xs:schema>\n````",
		"Source fragment target maps to goxsd-duplicate-target-2",
		"<a id=\"Target\"></a>\ncase distinct",
		"<!-- XHTML class: constraint schemaComp -->",
		"<!-- XHTML class: prod lhs -->",
		"Schema Representation Constraint: label",
		`<a id="list-target"></a>`,
		`<a id="code-target"></a>`,
		`<a id="term-target"></a>`,
		`<a id="definition-target"></a>`,
		`<a id="body-target"></a>`,
		`<a id="row-target"></a>`,
		`<a id="cell-target"></a>`,
	}
	for _, want := range wants {
		if !strings.Contains(string(first), want) {
			t.Errorf("output does not contain %q:\n%s", want, first)
		}
	}
}

func TestConvertRejectsMalformedOrNonXHTML(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"malformed", `<html xmlns="http://www.w3.org/1999/xhtml"><body><p></body></html>`, "parse XHTML at byte"},
		{"wrong namespace", `<html><body/></html>`, "root must be html in namespace"},
		{"unknown entity", `<html xmlns="http://www.w3.org/1999/xhtml"><body>&notAnEntity;</body></html>`, "parse XHTML at byte"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			_, err := Convert(strings.NewReader(test.input), "https://example.test/x.html", strings.Repeat("0", 64))
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("Convert() error = %v, want substring %q", err, test.want)
			}
		})
	}
}

func TestConvertRejectsNilReader(t *testing.T) {
	t.Parallel()
	_, err := Convert(nil, "https://example.test/x.html", strings.Repeat("0", 64))
	if err == nil || !strings.Contains(err.Error(), "read XHTML: reader must not be nil") {
		t.Fatalf("Convert(nil) error = %v, want contextual nil-reader error", err)
	}
}

func TestConvertPreservesBlocksNestedInListItems(t *testing.T) {
	t.Parallel()
	input := `<html xmlns="http://www.w3.org/1999/xhtml"><body>
<ul><li>outer condition<p>separate paragraph</p><ol><li>nested condition<pre xml:space="preserve">first
  second</pre></li></ol></li></ul>
</body></html>`
	output, err := Convert(strings.NewReader(input), "https://example.test/list.html", strings.Repeat("b", 64))
	if err != nil {
		t.Fatalf("Convert() error = %v", err)
	}
	markdown := string(output)
	wants := []string{
		"- outer condition\n\n  separate paragraph",
		"  1. nested condition",
		"     ```\n     first\n       second\n     ```",
	}
	for _, want := range wants {
		if !strings.Contains(markdown, want) {
			t.Errorf("output does not contain %q:\n%s", want, markdown)
		}
	}
	if strings.Contains(markdown, "outer condition separate paragraph") {
		t.Errorf("list block boundaries were flattened:\n%s", markdown)
	}
}

func TestConvertPreservesElementSyntaxTableauAsLiteral(t *testing.T) {
	t.Parallel()
	input := `<html xmlns="http://www.w3.org/1999/xhtml"><body>
<div class="reprBody"><div class="element-syntax-1"><a id="element-example" name="element-example">&lt;example</a><br />&#160;&#160;<b>count</b> = integer<br />&#160;&#160;size = (<var>large</var> | <var>small</var>) : medium&gt;<br /><em>&#160;&#160;Content: </em>(all | any*)<br />&lt;/example&gt;</div></div>
</body></html>`
	output, err := Convert(strings.NewReader(input), "https://example.test/structures.html", strings.Repeat("c", 64))
	if err != nil {
		t.Fatalf("Convert() error = %v", err)
	}
	markdown := string(output)
	want := "<a id=\"element-example\"></a>\n```\n<example\n  count = integer\n  size = (large | small) : medium>\n  Content: (all | any*)\n</example>\n```"
	if !strings.Contains(markdown, want) {
		t.Fatalf("output does not preserve element syntax tableau:\n%s", markdown)
	}
	if strings.Contains(markdown, "<example **count**") {
		t.Fatalf("element syntax was emitted as raw inline HTML:\n%s", markdown)
	}
}

func TestConvertPreservesNestedScrapProductionRows(t *testing.T) {
	t.Parallel()
	input := `<html xmlns="http://www.w3.org/1999/xhtml"><body>
<table class="scrap"><tbody><tr><td><strong>Test XPath expressions</strong></td></tr><tr><td><table><tbody>
<tr><td><a id="ta-Test" name="ta-Test"></a>[8]</td><td><code>Test</code></td><td>::=</td><td><code><a href="#ta-OrExpr"><i>OrExpr</i></a></code></td></tr>
</tbody><tbody>
<tr><td><a id="ta-BooleanExpr" name="ta-BooleanExpr"></a>[11]</td><td><code>BooleanExpr</code></td><td>::=</td><td><code>'(' OrExpr ')' | <a href="#ta-BooleanFunction">BooleanFunction</a> | <a href="#ta-ValueExpr">ValueExpr</a></code></td></tr>
</tbody></table></td></tr></tbody></table>
</body></html>`
	output, err := Convert(strings.NewReader(input), "https://example.test/structures.html", strings.Repeat("d", 64))
	if err != nil {
		t.Fatalf("Convert() error = %v", err)
	}
	markdown := string(output)
	wants := []string{
		"| <a id=\"ta-Test\"></a>\\[8\\] | `Test` | ::= | `OrExpr` |",
		"| <a id=\"ta-BooleanExpr\"></a>\\[11\\] | `BooleanExpr` | ::= | `'(' OrExpr ')' \\| BooleanFunction \\| ValueExpr` |",
	}
	for _, want := range wants {
		if !strings.Contains(markdown, want) {
			t.Errorf("output does not contain production row %q:\n%s", want, markdown)
		}
	}
	if strings.Contains(markdown, "`OrExpr``BooleanExpr`") {
		t.Fatalf("production rows were concatenated into adjacent code spans:\n%s", markdown)
	}
	assertMarkdownTablesValid(t, markdown)
}

func assertMarkdownTablesValid(t *testing.T, markdown string) {
	t.Helper()
	lines := strings.Split(markdown, "\n")
	for index := 0; index < len(lines); {
		if !strings.HasPrefix(lines[index], "| ") {
			index++
			continue
		}
		start := index
		for index < len(lines) && strings.HasPrefix(lines[index], "| ") {
			index++
		}
		block := lines[start:index]
		if len(block) < 2 {
			t.Fatalf("table at line %d has no delimiter row: %q", start+1, block)
		}
		width := len(markdownTableCells(block[0]))
		for rowIndex, row := range block {
			if got := len(markdownTableCells(row)); got != width {
				t.Fatalf("table at line %d row %d has %d columns, want %d: %q", start+1, rowIndex+1, got, width, row)
			}
		}
		for _, cell := range markdownTableCells(block[1]) {
			if strings.TrimSpace(cell) != "---" {
				t.Fatalf("table at line %d has invalid delimiter row %q", start+1, block[1])
			}
		}
	}
}

func markdownTableCells(row string) []string {
	var cells []string
	var cell strings.Builder
	escaped := false
	for _, character := range row {
		if escaped {
			cell.WriteRune(character)
			escaped = false
			continue
		}
		if character == '\\' {
			cell.WriteRune(character)
			escaped = true
			continue
		}
		if character == '|' {
			cells = append(cells, cell.String())
			cell.Reset()
			continue
		}
		cell.WriteRune(character)
	}
	cells = append(cells, cell.String())
	if len(cells) >= 2 && strings.TrimSpace(cells[0]) == "" && strings.TrimSpace(cells[len(cells)-1]) == "" {
		return cells[1 : len(cells)-1]
	}
	return cells
}

func TestConvertPreservesFormulaScriptsAndImages(t *testing.T) {
	t.Parallel()
	input := `<html xmlns="http://www.w3.org/1999/xhtml"><body>
<p>Numbers <var>m</var> × 2<sup><var>e</var></sup>, less than 2<sup>24</sup>; H<sub>2</sub>O.</p>
<p><img src="ProcMod-XPath.gif" alt="Processing Model Overview" /></p>
<p><a href="#figure"><img src="images/model.png" alt="Example [data] model" /></a></p>
</body></html>`
	output, err := Convert(strings.NewReader(input), "https://example.test/TR/xpath/Overview.html", strings.Repeat("e", 64))
	if err != nil {
		t.Fatalf("Convert() error = %v", err)
	}
	markdown := string(output)
	wants := []string{
		"Numbers m × 2<sup>e</sup>, less than 2<sup>24</sup>; H<sub>2</sub>O.",
		"![Processing Model Overview](<https://example.test/TR/xpath/ProcMod-XPath.gif>)",
		"[![Example \\[data\\] model](<https://example.test/TR/xpath/images/model.png>)](#figure)",
	}
	for _, want := range wants {
		if !strings.Contains(markdown, want) {
			t.Errorf("output does not contain %q:\n%s", want, markdown)
		}
	}
	for _, changed := range []string{"2e", "224", "H2O"} {
		if strings.Contains(markdown, changed) {
			t.Errorf("formula script was flattened to %q:\n%s", changed, markdown)
		}
	}
}

func TestConvertPreservesMultilinePreInsideTableCell(t *testing.T) {
	t.Parallel()
	input := `<html xmlns="http://www.w3.org/1999/xhtml"><body>
<table><tbody><tr><th>Schema example</th></tr><tr><td><pre xml:space="preserve">&lt;xs:schema&gt;
  &lt;xs:element name="item"/&gt;
&lt;/xs:schema&gt;</pre></td></tr></tbody></table>
</body></html>`
	output, err := Convert(strings.NewReader(input), "https://example.test/datatypes.html", strings.Repeat("f", 64))
	if err != nil {
		t.Fatalf("Convert() error = %v", err)
	}
	markdown := string(output)
	want := `<pre><code>&lt;xs:schema&gt;&#10;&#32;&#32;&lt;xs:element&#32;name=&#34;item&#34;/&gt;&#10;&lt;/xs:schema&gt;</code></pre>`
	if !strings.Contains(markdown, want) {
		t.Fatalf("output does not preserve table-cell pre content:\n%s", markdown)
	}
	if strings.Contains(markdown, "<xs:schema>") {
		t.Fatalf("table-cell pre content was emitted as raw HTML:\n%s", markdown)
	}
	assertMarkdownTablesValid(t, markdown)
}

func TestConvertRendersConstraintListHierarchy(t *testing.T) {
	t.Parallel()
	input := `<html xmlns="http://www.w3.org/1999/xhtml"><body>
<div class="p">Assessment has these aspects:
<div class="constraintlist">
<div class="clnumber">1<a id="local-validity" name="local-validity"> </a><span class="p">Determine local validity.</span></div>
<div class="clnumber">2 <span class="p">Combine descendant results:</span>
<div class="constraintlist">
<div class="clnumber">2.1 <span class="p">Check elements.</span></div>
<div class="clnumber">2.2 <span class="p">Check attributes.</span><pre xml:space="preserve">first
  second</pre></div>
</div></div>
</div></div>
</body></html>`
	output, err := Convert(strings.NewReader(input), "https://example.test/structures.html", strings.Repeat("1", 64))
	if err != nil {
		t.Fatalf("Convert() error = %v", err)
	}
	markdown := string(output)
	wants := []string{
		`1. <a id="local-validity"></a> Determine local validity.`,
		"2. Combine descendant results:",
		"   1. Check elements.",
		"   2. Check attributes.",
		"      ```\n      first\n        second\n      ```",
	}
	for _, want := range wants {
		if !strings.Contains(markdown, want) {
			t.Errorf("output does not contain %q:\n%s", want, markdown)
		}
	}
	for _, flattened := range []string{"1<a", "2 Determine", "2.1 Check"} {
		if strings.Contains(markdown, flattened) {
			t.Errorf("constraint numbering was flattened as %q:\n%s", flattened, markdown)
		}
	}
}

func TestConvertDuplicateAnchorAllocationAvoidsOriginalIDCollision(t *testing.T) {
	t.Parallel()
	input := `<html xmlns="http://www.w3.org/1999/xhtml"><body>
<p id="x">first</p><p id="x">duplicate</p><p id="goxsd-duplicate-x-2">real generated-looking ID</p>
</body></html>`
	output, err := Convert(strings.NewReader(input), "https://example.test/anchors.html", strings.Repeat("2", 64))
	if err != nil {
		t.Fatalf("Convert() error = %v", err)
	}
	markdown := string(output)
	wants := []string{
		`<a id="x"></a>`,
		`Source fragment x maps to goxsd-duplicate-x-3.`,
		`<a id="goxsd-duplicate-x-3"></a>`,
		`<a id="goxsd-duplicate-x-2"></a>`,
	}
	for _, want := range wants {
		if !strings.Contains(markdown, want) {
			t.Errorf("output does not contain %q:\n%s", want, markdown)
		}
	}
	for _, id := range []string{"x", "goxsd-duplicate-x-2", "goxsd-duplicate-x-3"} {
		if count := strings.Count(markdown, `<a id="`+id+`"></a>`); count != 1 {
			t.Errorf("output anchor %q count = %d, want 1:\n%s", id, count, markdown)
		}
	}
}
